version: "3.1"

services:
  mysql:
    image: mysql:latest
    container_name: mysql-server
    environment:
      MYSQL_ROOT_PASSWORD: liquimgm
    ports:  
      - 3333:3306
    volumes:
      - ./:/proyecto_sql